gpt_researcher:
  default:
    fast_llm: gpt_41mini_openrouter
    max_iterations: 3
    max_search_results_per_query: 5
    report_type: research_report
    search_engine: tavily
    tone: Objective
    description: Default configuration for GPT Researcher

  
  detailed:
     max_iterations : 5
     report_type: detailed_report

  legal_search:
    fast_llm: gpt_41mini_openrouter
    max_iterations: 2
    max_search_results_per_query: 2
    report_type: research_report
    report_source : "hybrid"
    search_engine: tavily
    tone: Objective
    description: Legal Assistant search
    document_urls:  # DOES NOT WORK .  Hydrid search need urls to documents
      - https://www.data.gouv.fr/datasets/legi-codes-lois-et-reglements-consolides
      - https://www.journal-officiel.gouv.fr

       