pgvector_configurations:
  default_local_container:
    postgres_user : tcl
    postgres_password : tcl
    postgres_host : localhost
    postgres_port : 6024
    postgres_db : ekg
    postgres_schema : public
    metadata_columns: 
    - name: len
      data_type: INTEGER
    - name: other_data
      data_type: TEXT
