cognee-demo:
  cv_demo_short:
    example_queries:
    - "Who has experience in design tools?"
    texts:
    - 'CV 1: Relevant
      Name: Dr. Emily Carter
      Contact Information:

      Email: emily.carter@example.com
      Phone: (555) 123-4567
      Summary:

      Senior Data Scientist with over 8 years of experience in machine learning and predictive analytics. Expertise in developing advanced algorithms and deploying scalable models in production environments.

      Education:

      Ph.D. in Computer Science, Stanford University (2014)
      B.S. in Mathematics, University of California, Berkeley (2010)
      Experience:

      Senior Data Scientist, InnovateAI Labs (2016 - Present)

      Skills:

      Programming Languages: Python, R, SQL
      Machine Learning: TensorFlow, Keras, Scikit-Learn
      Big Data Technologies: Hadoop, Spark
      Data Visualization: Tableau, Matplotlib'

    - 'CV 2: Relevant
      Name: Michael Rodriguez
      Contact Information:

      Email: michael.rodriguez@example.com
      Phone: (555) 234-5678
      Summary:

      Data Scientist with a strong background in machine learning and statistical modeling. Skilled in handling large datasets and translating data into actionable business insights.

      Education:

      M.S. in Data Science, Carnegie Mellon University (2013)
      B.S. in Computer Science, University of Michigan (2011)
      Experience:

      Senior Data Scientist, Alpha Analytics (2017 - Present)
      Developed machine learning models to optimize marketing strategies.
      '
  cv_demo:
    example_queries:
    - "Who has experience in design tools?"
    
    texts:
    - 'CV 1: Relevant
      Name: Dr. Emily Carter
      Contact Information:

      Email: emily.carter@example.com
      Phone: (555) 123-4567
      Summary:

      Senior Data Scientist with over 8 years of experience in machine learning and predictive analytics. Expertise in developing advanced algorithms and deploying scalable models in production environments.

      Education:

      Ph.D. in Computer Science, Stanford University (2014)
      B.S. in Mathematics, University of California, Berkeley (2010)
      Experience:

      Senior Data Scientist, InnovateAI Labs (2016 - Present)
      Led a team in developing machine learning models for natural language processing applications.
      Implemented deep learning algorithms that improved prediction accuracy by 25%.
      Collaborated with cross-functional teams to integrate models into cloud-based platforms.
      Data Scientist, DataWave Analytics (2014 - 2016)
      Developed predictive models for customer segmentation and churn analysis.
      Analyzed large datasets using Hadoop and Spark frameworks.
      Skills:

      Programming Languages: Python, R, SQL
      Machine Learning: TensorFlow, Keras, Scikit-Learn
      Big Data Technologies: Hadoop, Spark
      Data Visualization: Tableau, Matplotlib'

    - 'CV 2: Relevant
      Name: Michael Rodriguez
      Contact Information:

      Email: michael.rodriguez@example.com
      Phone: (555) 234-5678
      Summary:

      Data Scientist with a strong background in machine learning and statistical modeling. Skilled in handling large datasets and translating data into actionable business insights.

      Education:

      M.S. in Data Science, Carnegie Mellon University (2013)
      B.S. in Computer Science, University of Michigan (2011)
      Experience:

      Senior Data Scientist, Alpha Analytics (2017 - Present)
      Developed machine learning models to optimize marketing strategies.
      Reduced customer acquisition cost by 15% through predictive modeling.
      Data Scientist, TechInsights (2013 - 2017)
      Analyzed user behavior data to improve product features.
      Implemented A/B testing frameworks to evaluate product changes.
      Skills:

      Programming Languages: Python, Java, SQL
      Machine Learning: Scikit-Learn, XGBoost
      Data Visualization: Seaborn, Plotly
      Databases: MySQL, MongoDB '


    - 'CV 3: Relevant
      Name: Sarah Nguyen
      Contact Information:

      Email: sarah.nguyen@example.com
      Phone: (555) 345-6789
      Summary:

      Data Scientist specializing in machine learning with 6 years of experience. Passionate about leveraging data to drive business solutions and improve product performance.

      Education:

      M.S. in Statistics, University of Washington (2014)
      B.S. in Applied Mathematics, University of Texas at Austin (2012)
      Experience:

      Data Scientist, QuantumTech (2016 - Present)
      Designed and implemented machine learning algorithms for financial forecasting.
      Improved model efficiency by 20% through algorithm optimization.
      Junior Data Scientist, DataCore Solutions (2014 - 2016)
      Assisted in developing predictive models for supply chain optimization.
      Conducted data cleaning and preprocessing on large datasets.
      Skills:

      Programming Languages: Python, R
      Machine Learning Frameworks: PyTorch, Scikit-Learn
      Statistical Analysis: SAS, SPSS
      Cloud Platforms: AWS, Azure'

    - 'job_4 = """
      CV 4: Not Relevant
      Name: David Thompson
      Contact Information:

      Email: david.thompson@example.com
      Phone: (555) 456-7890
      Summary:

      Creative Graphic Designer with over 8 years of experience in visual design and branding. Proficient in Adobe Creative Suite and passionate about creating compelling visuals.

      Education:

      B.F.A. in Graphic Design, Rhode Island School of Design (2012)
      Experience:

      Senior Graphic Designer, CreativeWorks Agency (2015 - Present)
      Led design projects for clients in various industries.
      Created branding materials that increased client engagement by 30%.
      Graphic Designer, Visual Innovations (2012 - 2015)
      Designed marketing collateral, including brochures, logos, and websites.
      Collaborated with the marketing team to develop cohesive brand strategies.
      Skills:

      Design Software: Adobe Photoshop, Illustrator, InDesign
      Web Design: HTML, CSS
      Specialties: Branding and Identity, Typography'


    - 'CV 5: Not Relevant
      Name: Jessica Miller
      Contact Information:

      Email: jessica.miller@example.com
      Phone: (555) 567-8901
      Summary:

      Experienced Sales Manager with a strong track record in driving sales growth and building high-performing teams. Excellent communication and leadership skills.

      Education:

      B.A. in Business Administration, University of Southern California (2010)
      Experience:

      Sales Manager, Global Enterprises (2015 - Present)
      Managed a sales team of 15 members, achieving a 20% increase in annual revenue.
      Developed sales strategies that expanded customer base by 25%.
      Sales Representative, Market Leaders Inc. (2010 - 2015)
      Consistently exceeded sales targets and received the "Top Salesperson" award in 2013.
      Skills:

      Sales Strategy and Planning
      Team Leadership and Development
      CRM Software: Salesforce, Zoho
      Negotiation and Relationship Building'
  car_and_tech_compagnies:
    files:
    - https://raw.githubusercontent.com/topoteretes/cognee/refs/heads/main/examples/data/car_and_tech_companies.txt   
    
    ontology: https://raw.githubusercontent.com/topoteretes/cognee/refs/heads/main/examples/python/ontology_input_example/basic_ontology.owl
    
    example_queries:
    - "What are the exact cars and their types produced by Audi?"

  medical:
    files: 
    - ${paths.datasets}/scientific_papers/nutrients-13-01241.pdf
    - ${paths.datasets}/scientific_papers/TOJ-22-0073_152Mendoza.pdf
    ontology: https://raw.githubusercontent.com/topoteretes/cognee/refs/heads/main/examples/python/ontology_input_example/enriched_medical_ontology_with_classes.owl
    example_queries:
    - "What are common risk factors for Type 2 Diabetes?"
    - "What preventive measures reduce the risk of Hypertension?"
    - "What symptoms indicate possible Cardiovascular Disease?"
    - "I have blurred vision and a headache. What diease do I have?"
    - "What diseases are associated with Obesity?"

  chat_discussion:
  # WIP
  # taken from https://github.com/topoteretes/cognee/blob/main/examples/python/agentic_reasoning_procurement_example.py
    texts:
      - " Assistant: Hello! This is Sarah from TechSupply Solutions.
          Thanks for reaching out for your IT procurement needs.

          User: We're looking to procure 50 high-performance enterprise laptops.
          Specs: Intel i7, 16GB RAM, 512GB SSD, dedicated graphics card.
          Budget: $80,000. What models do you have?

          Assistant: TechSupply Solutions can offer Dell Precision 5570 ($1,450) and Lenovo ThinkPad P1 ($1,550).
          Both come with a 3-year warranty. Delivery: 2–3 weeks (Dell), 3–4 weeks (Lenovo).

          User: Do you provide bulk discounts? We're planning another 200 units next quarter.

          Assistant: Yes! Orders over $50,000 get 8% off.
          So for your current order:
          - Dell = $1,334 each ($66,700 total)
          - Lenovo = $1,426 each ($71,300 total)

          And for 200 units next quarter, we can offer 12% off with flexible delivery."

