# zzz ReAct Agent Demos Configuration  aaaaaaaa
  react_agent_demos:
  - name: "Weather"
    tools:  
      - my_custom_weather
    mcp_servers:
      - "weather"
      - "playwright"
    examples: ()
      - "What is the wind in NY?"
      - "Quel temps fait-il à Toulouse"

    
  - name: "Weather & PowerPoint"
    mcp_servers:
      - "weather"
      - "ppt"
    examples:
      - "Get weather in Toulouse today. Create a PowerPoint file about it and usual climate in Toulouse"
    
  - name: "Web Research"
    mcp_servers:
      - "playwright"
    examples:
      - "Research the latest AI developments on OpenAI's website"
      - "Find information about quantum computing on IBM's website"
      - "Connect to atos.net with a browser, find the page with blogs, and get list of recent blog articles"
  
  - name: "Ma super idée"
    mcp_servers:
      - "ppt"
      - filesystem
    examples:
      - "write a powerpoint with the current directory. Create one slide with directy list."
    