# ReAct Agent Demos Configuration
react_agent_demos:
  - name: "Weather & PowerPoint"
    mcp_servers:
      - "weather"
      - "ppt"
#      - "tavily-mcp"
    examples:
      - "Get weather in  San Francisco today. Create a PowerPoint file about it and usual climate in San Francisco and save it in temp directory"
    
  - name: "Web Research"
    mcp_servers:
      - "playwright"
    examples:
      - "Research the latest AI developments on OpenAI's website"
      - "Find information about quantum computing on IBM's website"
      - "Connect to atos.net with a browser, find the page with blogs, and get list of recent blog articles"
  
  - name: "Ma super idée"
    mcp_servers:
      - "ppt"
      - filesystem
    examples:
      - "write a powerpoint with the current directory. Create one slide with directy list."
    