################
# Application configuration file 
################


# Configuration leverage OmegaConf solvers. See :
# https://omegaconf.readthedocs.io/en/2.3_branch/usage.html#variable-interpolation

paths:
  data_root : ${oc.env:HOME}
  project : ${oc.env:PWD}
  src: ${paths.project}/src
  config: ${paths.project}/config
  demo_conf: ${paths.project}/config/demos


# Other config files merged to this one at launch time
merge:
  - ${paths.config}/baseline.yaml
  - ${paths.config}/overrides.yaml
  - ${paths.config}/mcp_servers.yaml

# Default configuration, as defined in baseline.yaml, overrides.yaml, here, or elsewhere.
# It can be overidden by 'BLUEPRINT_CONFIG' environment variable, or in code

default_config: ${oc.env:BLUEPRINT_CONFIG,training_openrouter}

#### 
# UI Configuration : list of Streamlit pages, authentication, ... 
####    
ui:
  app_name : GenAI Lab and Practicum
  pages_dir : ${paths.src}/webapp/pages
  navigation:
    settings:
      - 0_welcome.py
      - 1_runnable_playground.py
      - 3_configuration.py
      - 4_CLI_runner.py
    demos:
      - 2_maintenance_agent.py
      - 5_mon_master.py
      - 7_deep_search_agent.py
      - 12_reAct_agent.py
      - 10_codeAct_agent.py
      - 14_graph_RAG.py
      - 18_residio_anonymization.py



auth:
  enabled: ${oc.env:BASIC_AUTH_ENABLED,false}
  config_file: ${paths.config}/basic_auth.yaml

#####
# modules  with CLI commands to be loaded
####
commands:
  modules:
    - src.ai_core.cli_commands
    - src.ai_extra.cli_commands
    - src.webapp.cli_commands
