################
# Application configuration file 
################

# cSpell:disable

# Configuration leverage OmegaConf solvers. See :
# https://omegaconf.readthedocs.io/en/2.3_branch/usage.html#variable-interpolation

paths:
  data_root : ${oc.env:HOME}
  project : ${oc.env:PWD}
  src: ${paths.project}/src
  config: ${paths.project}/config


# Other config files merged to this one
merge:
  - ${paths.config}/mcp_servers.yaml
  - ${paths.config}/baseline.yaml
  - ${paths.config}/overrides.yaml

#### 
# UI Configuration : list of Streamlit pages, ... 
####    
ui:
  app_name : GenAI Lab and Practicum
  pages_dir : ${paths.src}/webapp/pages

  
default_config: carbon_monitor_local   # can be overidden by 'BLUEPRINT_CONFIG' environment variable
