################
# Application configuration file 
################


# Configuration leverage OmegaConf solvers. See :
# https://omegaconf.readthedocs.io/en/2.3_branch/usage.html#variable-interpolation

paths:
  data_root : ${oc.env:HOME}
  project : ${oc.env:PWD}
  src: ${paths.project}/src
  config: ${paths.project}/config
  demo_conf: ${paths.project}/config/demos


# Other config files merged to this one
merge:
  - ${paths.config}/baseline.yaml
  - ${paths.config}/overrides.yaml
  - ${paths.config}/mcp_servers.yaml
  # demos configurations   
  - ${paths.demo_conf}/codeact_agent.yaml
  - ${paths.demo_conf}/react_agent.yaml
  - ${paths.demo_conf}/graph_rag.yaml

# Default configuration, as defined in baseline.yaml, overrides.yaml, here, or elsewhere.
# It can be overidden by 'BLUEPRINT_CONFIG' environment variable, or in code

default_config: training_edenai   

#### 
# UI Configuration : list of Streamlit pages, ... 
####    
ui:
  app_name : GenAI Lab and Practicum
  pages_dir : ${paths.src}/webapp/pages

  
