# MCP Servers configuration.  
# Similar to their usual JSON equivalent, but loaded from OmegaConf so variable are resolved.
mcpServers:
  filesystem:
      command: npx
      args: 
      - "-y"
      - "@modelcontextprotocol/server-filesystem"
      - ${paths.project}

  pubmed:
      command: uvx
      args: ["--quiet", "pubmedmcp@0.1.3"]
      description: Provides access to PubMed medical research database
      example : "Find relevant studies on alcohol hangover and treatment."
      disabled: true

  playwright:
    command: npx
    args: 
    - "@playwright/mcp@latest"
    - "--headless"

  github:
    command: npx
    args:  ["-y", "@modelcontextprotocol/server-github"]
    env:
      GITHUB_PERSONAL_ACCESS_TOKEN: ${oc.env:GITHUB_TOKEN}
    disabled: true

  tavily-mcp: 
    command: npx
    args: [ "-y" ,"tavily-mcp"]
    env: 
      TAVILY_API_KEY : ${oc.env:TAVILY_API_KEY}
  #  disabled: true
    
  sequential-thinking: 
    command: npx
    args: ["-y", "@modelcontextprotocol/server-sequential-thinking"]
    
  ppt: 
    command: uvx
    args: ["--from", "office-powerpoint-mcp-server", "ppt_mcp_server"]

  math:
      command: uv
      args: 
        - run 
        - ${paths.src}/mcp_server/math_server.py
      disabled: true
    
  weather:
      command: uv
      args: 
        - run 
        - ${paths.src}/mcp_server/weather_server.py
      disabled: false
