
#### 
# Overridden configurations
# Set by environment variable "BLUEPRINT_CONFIG", or by the 'default_config' key, or in code
####   

training_local:
  llm:
    default_model:  llama32_3_ollama
  embeddings:
    default_model: artic_22_ollama

training_edenai:
  llm:
    default_model: gpt_4omini_edenai
    cache : memory
  embeddings:
    default_model: ada_002_edenai
  onedrive_data: ${oc.env:ONEDRIVE, null}/_ongoing/training GenAI

training_openrouter:
  llm:
    default_model: gpt_41mini_openrouter
    cache : memory
  embeddings:
    default_model: ada_002_edenai
  onedrive_data: ${oc.env:ONEDRIVE, null}/_ongoing/training GenAI

training_azure:
  llm:
    default_model: gpt_4omini_azure
  embeddings:
    default_model: ada_002_azure
  onedrive_data: ${oc.env:ONEDRIVE, null}/_ongoing/training GenAI


training_openai:
  llm:
    default_model: gpt_4omini_openai
  embeddings:
    default_model: ada_002_openai
  dummy:
    bar: foo

pytest:
  llm:
    default_model: gpt_4omini_edenai
  embeddings:
    default_model: ada_002_edenai