
#### 
# Overridden configurations
# Set by environment variable "BLUEPRINT_CONFIG", or by the 'default_config' key, or in code
####   

training_local:
  llm:
    default_model:  llama32_3_ollama
  embeddings:
    default_model: artic_22_ollama

training_edenai:
  llm:
    default_model: gpt_4omini_edenai
    cache : memory
  embeddings:
    default_model: ada_002_edenai

training_openrouter:
  llm:
    default_model: gpt_41mini_openrouter
    cache : memory
  embeddings:
    default_model: bge_m3_deepinfra

training_azure:
  llm:
    default_model: gpt_4omini_azure
  embeddings:
    default_model: ada_002_azure


training_openai:
  llm:
    default_model: gpt_4omini_openai
  embeddings:
    default_model: ada_002_openai
  dummy:
    bar: foo

pytest:
  llm:
    default_model: gpt_4omini_edenai
  embeddings:
    default_model: ada_002_edenai

container: 
  paths:
    data_root: /data
    project: /app
    src: ${paths.project}/src
    config: ${paths.project}/config
    demo_conf: ${paths.project}/config/demos
  llm:
    default_model: gpt_41mini_openrouter
    cache: sqlite
    cache_path: ${paths.data_root}/llm_cache/langchain.db
  embeddings:
    default_model: bge_m3_deepinfra
    cache: ${paths.data_root}/hf_models
  vector_store:
    default: Chroma
    path: ${paths.data_root}/vector_store
    default_collection: "default_collection"
  monitoring: 
    default:  langsmith
  external_data: ${paths.data_root}/external

ekg_local:
  default_model: kimi_k2_openrouter
  cli:
    commands:  
    - src.ai_core.cli_commands:register_commands
    - src.demos.ekg.cli_commands:register_commands